name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      GITEA_SERVER: ${{ vars.ADDRESS_GITEA_SERVER}}
      GITEA_REGISTRY: ${{ vars.ADDRESS_GITEA_REGISTRY }}
      GITEA_TOKEN: ${{ secrets.REPO_GITEA_TOKEN }}
      PROJECT_NAME: ${{ vars.project_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ secrets.REPO_USERNAME }} 
          password: ${{ secrets.REPO_GITEA_TOKEN }}

      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v2
        env:
          ACTIONS_RUNTIME_TOKEN: ''
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:1.0.0

      - name: Build and Push Docker Image to Gitea Release
        run: |
          docker image ls
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:latest ${{ env.GITEA_REGISTRY }}/${{ env.PROJECT_NAME }}:1.0.0
          docker push ${{ env.GITEA_REGISTRY }}/${{ env.PROJECT_NAME }}:latest
          docker push ${{ env.GITEA_REGISTRY }}/${{ env.PROJECT_NAME }}:1.0.0
      