name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      GITEA_SERVER: https://git.rehounou.ca
      GITEA_REGISTRY: git.rehounou.ca
      GITEA_TOKEN: ${{ secrets.REPO_GITEA_TOKEN }}
      PROJECT_NAME: cal_heatmap

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ secrets.REPO_USERNAME }} 
          password: ${{ secrets.REPO_GITEA_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        env:
          ACTIONS_RUNTIME_TOKEN: ''
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cal_heatmap:latest
            ${{ secrets.DOCKER_USERNAME }}/cal_heatmap:1.0.0

      - name: Build and Push Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/cal_heatmap:latest git.rehounou.ca/remi/cal_heatmap:1.0.0
          docker push git.rehounou.ca/remi/cal_heatmap:latest
          docker push git.rehounou.ca/remi/cal_heatmap:1.0.0
      